### ISSUE TITLE
pre-preprocess data (US1)

### ISSUE THREAD

**Issue by sbgonenc** [2022ADS-4/spotlight#1]
User Stroy 1 -- US1- As an Analyst I want to be able to analyze the data to understand it and to monitor it, so that a Recommender can be done. Tasks.

- [x] Store data in GitHub (small file)
--
- [x]  Merge data
- [x] Look at the NaNs
- [ ] Look at the categories
- [x] Check correlations
- [ ] Look at the distribution (balance)
- [x] Visualize the data summary

**Comment by hannahmabel** [comment]
Old issue, has been split into many smaller issues.
