### ISSUE TITLE
process data and model

### ISSUE THREAD

**Issue by sbgonenc** [2022ADS-4/spotlight#2]
US2- As a Recommender Developer, I want to obtain the recommendations in batch, so that a Recommender can be done.

------
2.1
------
- [ ] Dealing with missing values
- [ ] Remove outliers
- [ ] Deal with categorical data (encode)
- [ ] Select relating features
- [ ] Normalize the data

--------
2.2
------
- [ ] Split into train, validation and test
- [ ] Train many models and select the best
- [ ] Report the test accuracy

**Comment by Alllessia** [comment]
This issue was old.
