### ISSUE TITLE
Create a PowerPoint Presentation for the Product Owner

### ISSUE THREAD

**Issue by hannahmabel** [2022ADS-4/spotlight#29]
- [ ] Make slides about User Story 1.1 for the powerpoint presentation @Alllessia 
- [ ] Make slides about User Story 1.2 for the powerpoint presentation @sbgonenc 
- [ ] Make slides about User Story 2.1 for the powerpoint presentation @juliale102 
- [ ] Make slides about User Story 2.2 for the powerpoint presentation @hannahmabel

**Comment by Alllessia** [comment]
Duplicate issue. Refer to #30

**Comment by Alllessia** [comment]
Duplicated issue. Refer to #30
