### ISSUE TITLE
Create a PowePoint Presentation for the Product Owner

### ISSUE THREAD

**Issue by hannahmabel** [2022ADS-4/spotlight#30]
For the powerpoint presentation of the demo

**Comment by Alllessia** [comment]
- [ ] Make slides about User Story 1.1 for the powerpoint presentation @Alllessia 
- [ ] Make slides about User Story 1.2 for the powerpoint presentation @sbgonenc 
- [ ] Make slides about User Story 2.1 for the powerpoint presentation @juliale102 
- [ ] Make slides about User Story 2.2 for the powerpoint presentation @hannahmabel
